library(lpSolveAPI)
lprec<-make.lp(20,8)
lp.control(lprec,sense="max") #Maximum Function
set.type(lprec,columns = c(1:8),type = "integer")  #Integer restriction
set.objfn(lprec,c(4,6.5,5.9,5.4,5.15,10,8.4,6.25)) #Objective Function
set.row(lprec,1,c(40,50,80,60,45,60,30,25),indices = c(1:8)) #20 Contraints
set.row(lprec,2,1000,indices =1)
set.row(lprec,3,1000,indices =2)
set.row(lprec,4,1000,indices =3)
set.row(lprec,5,1000,indices =4)
set.row(lprec,6,1000,indices =5)
set.row(lprec,7,1000,indices =6)
set.row(lprec,8,1000,indices =7)
set.row(lprec,9,1000,indices =8)
set.row(lprec,10,40,indices =1)
set.row(lprec,11,50,indices =2)
set.row(lprec,12,80,indices =3)
set.row(lprec,13,60,indices =4)
set.row(lprec,14,45,indices =5)
set.row(lprec,15,60,indices =6)
set.row(lprec,16,30,indices =7)
set.row(lprec,17,25,indices =8)
set.row(lprec,18,c(40,50,80),indices = c(1,2,3))
set.row(lprec,19,c(60,45,60),indices = c(4,5,6))
set.row(lprec,20,c(30,25),indices = c(7,8))
set.constr.type(lprec,types = "<=",constraints = 1)    #Inequalities
set.constr.type(lprec,types = ">=",constraints = 2)
set.constr.type(lprec,types = rep(">="),constraints =3)
set.constr.type(lprec,types = rep(">="),constraints =4)
set.constr.type(lprec,types = rep(">="),constraints =5)
set.constr.type(lprec,types = rep(">="),constraints =6)
set.constr.type(lprec,types = rep(">="),constraints =7)
set.constr.type(lprec,types = rep(">="),constraints =8)
set.constr.type(lprec,types = rep(">="),constraints =9)
set.constr.type(lprec,types = rep(">="),constraints =10)
set.constr.type(lprec,types = rep(">="),constraints =11)
set.constr.type(lprec,types = rep(">="),constraints =12)
set.constr.type(lprec,types = rep(">="),constraints =13)
set.constr.type(lprec,types = rep(">="),constraints =14)
set.constr.type(lprec,types = rep(">="),constraints =15)
set.constr.type(lprec,types = rep(">="),constraints =16)
set.constr.type(lprec,types = rep(">="),constraints =17)
set.constr.type(lprec,types = rep("<="),constraints =18)
set.constr.type(lprec,types = rep("<="),constraints =19)
set.constr.type(lprec,types = rep("<="),constraints =20)
set.rhs(lprec,c(2500000,rep(0,8),rep(100000,8),rep(1000000,3)),constraints = c(1:20)) # Right Hand Side Values
solve(lprec)
get.objective(lprec)
get.variables(lprec)
get.constraints(lprec)
