---
title: "Assignment 6"
author: "oakintoy"
date: "November 6, 2019"
output: pdf_document
---
Q1 

```{r}
x <- matrix(c(150,400,320,520,350,320,0.2,0.7,1.2,2,1.2,0.7),ncol = 2)
y <- matrix(c(14000,14000,42000,28000,19000,14000,3500,21000,10500,42000,25000,15000),ncol = 2)
colnames(x) <- c("Staff","Supplies")
colnames(y) <- c("Reim","Priv")
x
y
```

```{r}
#install.packages("Benchmarking")
library(Benchmarking)
FDH <- dea(x,y,RTS = "fdh")             
FDH
peers(FDH)                          
lambda(FDH)
CRS <- dea(x,y,RTS = "crs")         
CRS
peers(CRS)                           
lambda(CRS)
VRS <- dea(x,y,RTS = "vrs")            
VRS
peers(VRS)                           
lambda(VRS)
IRS <- dea(x,y,RTS = "irs")           
IRS
peers(IRS)                             
lambda(IRS)
DRS <- dea(x,y,RTS = "drs")         
DRS
peers(DRS)                            
lambda(DRS)
FRH <- dea(x,y,RTS = "add")           
FRH
peers(FRH)                             
lambda(FRH)  
```

Q2

```{r}
library(lpSolveAPI)
goal <- read.lp("Goal_1_oakintoy_6_Qantitative_modline.lp")
goal
``` 
## Solve
```{r}
solve(goal)
get.objective(goal)
get.variables(goal)
```